class Config :
    system_img = "/home/hardik/Phone/OOS/7PRO/OOS7P_958_V2/gsi2rom/sys.img"
    vendor_img = "/home/hardik/Phone/OOS/7PRO/OOS7P_958_V2/gsi2rom/vend.img"
    boot_img = "/home/hardik/Phone/OOS/7PRO/OOS7P_958_V2/gsi2rom/boot.img"
    rom_base_git = "https://github.com/oddlyspaced/oos-violet-rom-base.git"    
    device = "violet"
    porter = "BallBoxer"
    android_version = "9"
    port = "OnePlus 7 Pro"
    date = "7 July 2019"
    security = "May 1 2019"